### ISSUE TITLE
PermissionError: [Errno 13] Permission denied while installing Luna Studio in Windows 10

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-manager#159]
@niutech commented on [Tue Feb 13 2018](https://github.com/luna/luna-studio/issues/818)

I cannot install Luna Studio 1.1 beta in Windows 10 using `lunaInstaller.exe` run as Administrator:

```
[19272] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
PermissionError: [Errno 13] Permission denied: 'C:\\tmp\\luna\\luna-studio-windows-1\\luna-studio\\user-config\\atom\\packages\\luna-dark-ui\\.git\\objects\\pack\\pack-41350ad5cdfa9a7c9eaa1bb714594cce132e042d.idx'
error running: C:\tmp\luna\tar2.exe untar luna-studio-windows-1.1.tar.gz C:\tmp\luna\luna-studio-windows-1
exit status: -1
stderr: [19272] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
PermissionError: [Errno 13] Permission denied: 'C:\\tmp\\luna\\luna-studio-windows-1\\luna-studio\\user-config\\atom\\packages\\luna-dark-ui\\.git\\objects\\pack\\pack-41350ad5cdfa9a7c9eaa1bb714594cce132e042d.idx'
```

**Comment by sylwiabr** [comment]
should be solved in new upcoming package (1.1.1)

**Comment by BatmanAoD** [comment]
@sylwiabr Should this also be resolved in 1.2? I got this error:

```
during copy from: C:\tmp\luna\luna-studio-windows-1\luna-studio to: C:\Program Files\LunaStudio\1.2
Exception: MoveFileEx "C:\\tmp\\luna\\luna-studio-windows-1\\luna-studio" "C:\\Program Files\\LunaStudio\\1.2": permission denied (Access is denied.)
```

I believe I'm running with administrator privileges because I was given the elevate-privilege prompt (the "user account control" window with the "make changes to your device" text).

**Comment by BatmanAoD** [comment]
Re-running *as an Administrator* (from the right-click menu in Explorer) seems to have finished in a successful install. So it seems the privilege-elevation prompt is a bit misleading.

**Comment by mikusp** [comment]
From our experience, the "permission denied" error is ephemeral and rerunning the installation often succeeds. We don't know why Windows behaves like this. It was suggested that AV programs can interfere, but it isn't proven.

**Comment by Botronicz** [comment]
I'm still getting this error on Windows 10 Pro: 
during copy from: C:\Users\xxxx\AppData\Local\Temp\luna17497\luna-studio-windows-1 to: C:\Program Files\LunaStudio\1.7
Exception: MoveFileEx "C:\\Users\\xxxx\\AppData\\Local\\Temp\\luna17497\\luna-studio-windows-1" "C:\\Program Files\\LunaStudio\\1.7": permission denied (Access is denied.)
Manager version: 1.2

This was from the GUI installer, but I get the same error from the command line installer.

I've run both installers (command line and GUI) numerous times (2-3 times per combination), with and without administrator privileges.  I cannot get Luna 1.7 installed on Windows 10.

Any suggestions of what to try?

**Comment by mwu-tow** [comment]
@Botronicz 
Thanks for reporting this issue!

Hard to say, I can install without a problem using the current luna-manager on Windows 10 Pro. I do get that error only when I run luna-manager without administrator privileges. 

I'm not an expert on the matter, but I assume that error can mean two things:
1) permission denied to write the folder — please reconfirm that you run command line luna-manager as administrator (GUI shouldn't allow to be run without privileges). Make sure that as administrator you can create directories in `C:\Program Files` — eg. try running in administrator command prompt `mkdir "C:\Program Files\LunaStudio"`. Does it work?
Please try specifying other writable installation directorty in the command line installer (eg. your home directory). Does it help?
2) permission denied to remove temporary folder.
Try immediately after failed installation removing the directory given in the error message (e.g. `C:\Users\xxxx\AppData\Local\Temp\luna17497\luna-studio-windows-1`)? Does it work?
Such errors might be caused by third-party software that opens our temporary files — that includes AV software but also some windows explorer shell extensions. Do you use AV software or anything that might be locking our temporary files?

We will also work on improving our installer robustness but it would be great if we were able to get some clue as to what is causing the problem you have encountered.

**Comment by Botronicz** [comment]
AV software was indeed the problem.

I had IOBit Malware Fighter running when I'd previously tried all the installs.  I closed Malware Fighter and the install completed (with Administrator privileges).
This is the first time I've ever had to close an AV program in order for an install to complete.  I've been doing development work on Windows since version 1.0, so that a lot of software installations!

**Comment by mwu-tow** [comment]
@Botronicz Thanks for letting us know! Luna contains ~200 MB of binaries, AV software likely needs some time to properly go through them and is apparently locking us out from our files for a while. 

I believe Windows Defender is able to do this in a way that just delays us instead of outright failing with permission denied — but people use various AV software and we need to deal with it. While we cannot account for every possible AV software, there are things we can do to make our installation process less vulnerable — like avoiding unnecessary file moves, adding retries or falling back onto copy.
