### ISSUE TITLE
Failed to install Luna Studio 1.5.100.6

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-manager#205]
The following appeared when I tried updating my Luna Studio installation on Windows.

![obraz](https://user-images.githubusercontent.com/1548407/47014281-0e26a980-d14a-11e8-9b7b-dac03552e8d2.png)

```
[24004] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\tmp\\luna20353\\luna-studio-windows-1\\luna-studio\\third-party\\Atom\\resources\\app\\apm\\node_modules\\npm-registry-client\\node_modules\\npmlog\\node_modules\\gauge\\node_modules\\string-width\\node_modules\\is-fullwidth-code-point\\node_modules\\number-is-nan\\package.json'
error running: C:\tmp\luna20353\tar2.exe untar luna-studio-windows-1.5.100.6.tar.gz C:\tmp\luna20353\luna-studio-windows-1
exit status: -1
stderr: [24004] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\tmp\\luna20353\\luna-studio-windows-1\\luna-studio\\third-party\\Atom\\resources\\app\\apm\\node_modules\\npm-registry-client\\node_modules\\npmlog\\node_modules\\gauge\\node_modules\\string-width\\node_modules\\is-fullwidth-code-point\\node_modules\\number-is-nan\\package.json'

Manager version: 1.1.4
```

The said path is 260 characters long, which exceeds MAX_PATH — I guess the tar2 (or whatever is source of the error)  is not long-path aware.
Also, the error message GUI looks ugly.

**Comment by mwu-tow** [comment]
FWIW 7zip can extract the archive correctly into temp, handling the overlong paths correctly.

**Comment by piotrMocz** [comment]
The manager is now using 7Zip and everything seems to work.

**Comment by sylwiabr** [comment]
Manager works fine, we have to check the installer when it will be released.

**Comment by sylwiabr** [comment]
Ok, the installer is working as well. Jus progress updates needs to be sorted out (stops at Downloading 100%, then freeze and gets to Installing 85%)
