### ISSUE TITLE
AccessDenied when trying to install Luna via luna-manager.exe

### ISSUE THREAD

**Issue by oconnor0** [luna/luna-manager#250]
### General Summary

AccessDenied when trying to install Luna via luna-manager.exe

### Steps to Reproduce

When I attempt to install, I get the following:

```
PS C:\Users\Oconnor\Downloads> .\luna-manager.exe install

Available components:
  - luna-studio
Select component to be installed [luna-studio]:

Available luna-studio versions:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
Select version to be installed [1.9]:

Select installation path for luna-studio [C:\Program Files]: c:\luna
Download completed!
Download completed!
Unpacking archive: C:\Users\Oconnor\AppData\Local\Temp\luna15629\luna-studio-windows-1.9.7z

Copying files from C:\Users\Oconnor\AppData\Local\Temp\luna15629\luna-studio-windows-1 to C:\luna\LunaStudio\1.9

Do you want to export C:\luna\LunaStudio\current\bin\main\luna-studio.exe? [yes]/no

error running: C:\luna\LunaStudio\1.9\config\windows\installAll.bat
exit status: 5
stderr: WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

Manager version: 1.1.5
```

### Expected Result

I would expect the install to succeed.

### Actual Result

Some files end up in `c:\luna` and `C:\luna\LunaStudio\1.9\bin\main\luna-studio.exe` does not start successfully when run. It pops up a dialog box that says:

```
Received ExitFailure 200 when running
Raw command:
"C:\\luna\\LunaStudio\\1.9\\config\\windows\\start.bat
```

**Comment by oconnor0** [comment]
For what it is worth, I get the same error when running the above in `cmd` rather than `Power Shell`.
